# This is a basic workflow to help you get started with Actions

name: Sunniberg Application Pipeline 4LIFE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "feature/**", "release/**", "bugfix/**", "hotfix/**" ]
  pull_request:
    branches: [ "main", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job wil run on
    runs-on: ubuntu:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run YARN TSC
        run: yarn tsc
      - name: Run YARN LINT
        run: yarn lint
      - name: Run YARN PRETTIER
        run: yarn prettier:check
      - name: Run Unit Tests
        run: yarn test:ci
      - name: Run Cypress Tests
        run: yarn cy:ci
